# Generated by Django 3.2.12 on 2022-04-09 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('model_year', models.IntegerField()),
                ('car_insurance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RentPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('paid_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit/Debit Card', 'Credit/Debit Card'), ('PayPal', 'PayPal')], max_length=40)),
                ('rent_from', models.DateField()),
                ('rent_to', models.DateField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
