# Generated by Django 3.2.12 on 2022-04-10 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcar',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rentplace',
            name='id',
        ),
        migrations.AddField(
            model_name='rentcar',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='rentplace',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rentplace',
            name='bathrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rentplace',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rentplace',
            name='rooms',
            field=models.PositiveIntegerField(),
        ),
    ]
