# Generated by Django 3.2.12 on 2022-05-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0004_auto_20220410_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcar',
            name='model_year',
            field=models.PositiveIntegerField(),
        ),
    ]
